<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita390bf8bca9788a09cd746fafc02ae20
{
    public static $prefixLengthsPsr4 = array (
        'K' => 
        array (
            'Kszkl\\Calendar\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Kszkl\\Calendar\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita390bf8bca9788a09cd746fafc02ae20::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita390bf8bca9788a09cd746fafc02ae20::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita390bf8bca9788a09cd746fafc02ae20::$classMap;

        }, null, ClassLoader::class);
    }
}
